server:
  port: 9000
spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  profiles:
    active:
      - "prod"
  application:
    name: "cards"
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"