server:
  port: 8090
spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8071
  application:
    name: loans
  profiles:
    active:
      - "prod"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"