services:

  configserver:
    image: znaji/configserver:v2
    container_name: configserver-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: znaji/accounts:v1
    container_name: accounts-ms
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: znaji/cards:v1
    container_name: cards-md
    ports:
      - 9000:9000
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: znaji/loans:v1
    container_name: loans-ms
    ports:
      - 8090:8090
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: bridge