services:

  configserver:
    image: znaji/configserver:v3
    container_name: configserver-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: znaji/eurekaserver:v3
    container_name: eurekaserver
    ports:
      - 8070:8070
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: znaji/accounts:v3
    container_name: accounts-ms
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: znaji/cards:v3
    container_name: cards-md
    ports:
      - 9000:9000
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: znaji/loans:v3
    container_name: loans-ms
    ports:
      - 8090:8090
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-eureka-config
  loans1:
    image: znaji/loans:v3
    container_name: loans-ms1
    ports:
      - 8091:8090
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: bridge